[package]
  cjc-version = "1.0.0"
  name = "cjsfml"
  description = "SFML library bindings"
  version = "2.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  compile-option = "--dy-std -O2"
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  cenum = { path = "../cenum" }
  ctemplate = { path = "../ctemplate" }
  endian = { path = "../endian" }

[ffi.c]
  csfml-audio = { path = "../csfml" }
  csfml-graphics = { path = "../csfml" }
  csfml-system = { path = "../csfml" }
  csfml-window = { path = "../csfml" }
